export const AVAILABLE_CITIES = [
  { city: "Anchorage", country: "United States", timezone: "America/Anchorage", flag: "🇺🇸" },
  { city: "Auckland", country: "New Zealand", timezone: "Pacific/Auckland", flag: "🇳🇿" },
  { city: "Bangkok", country: "Thailand", timezone: "Asia/Bangkok", flag: "🇹🇭" },
  { city: "Berlin", country: "Germany", timezone: "Europe/Berlin", flag: "🇩🇪" },
  { city: "Buenos Aires", country: "Argentina", timezone: "America/Argentina/Buenos_Aires", flag: "🇦🇷" },
  { city: "Cairo", country: "Egypt", timezone: "Africa/Cairo", flag: "🇪🇬" },
  { city: "Cape Town", country: "South Africa", timezone: "Africa/Johannesburg", flag: "🇿🇦" },
  { city: "Casablanca", country: "Morocco", timezone: "Africa/Casablanca", flag: "🇲🇦" },
  { city: "Chicago", country: "United States", timezone: "America/Chicago", flag: "🇺🇸" },
  { city: "Denver", country: "United States", timezone: "America/Denver", flag: "🇺🇸" },
  { city: "Dubai", country: "UAE", timezone: "Asia/Dubai", flag: "🇦🇪" },
  { city: "Honolulu", country: "United States", timezone: "Pacific/Honolulu", flag: "🇺🇸" },
  { city: "Hong Kong", country: "Hong Kong", timezone: "Asia/Hong_Kong", flag: "🇭🇰" },
  { city: "Istanbul", country: "Turkey", timezone: "Europe/Istanbul", flag: "🇹🇷" },
  { city: "Johannesburg", country: "South Africa", timezone: "Africa/Johannesburg", flag: "🇿🇦" },
  { city: "Lagos", country: "Nigeria", timezone: "Africa/Lagos", flag: "🇳🇬" },
  { city: "London", country: "United Kingdom", timezone: "Europe/London", flag: "🇬🇧" },
  { city: "Los Angeles", country: "United States", timezone: "America/Los_Angeles", flag: "🇺🇸" },
  { city: "Mexico City", country: "Mexico", timezone: "America/Mexico_City", flag: "🇲🇽" },
  { city: "Moscow", country: "Russia", timezone: "Europe/Moscow", flag: "🇷🇺" },
  { city: "Nairobi", country: "Kenya", timezone: "Africa/Nairobi", flag: "🇰🇪" },
  { city: "New Delhi", country: "India", timezone: "Asia/Kolkata", flag: "🇮🇳" },
  { city: "New York", country: "United States", timezone: "America/New_York", flag: "🇺🇸" },
  { city: "Paris", country: "France", timezone: "Europe/Paris", flag: "🇫🇷" },
  { city: "Reykjavik", country: "Iceland", timezone: "Atlantic/Reykjavik", flag: "🇮🇸" },
  { city: "Rio de Janeiro", country: "Brazil", timezone: "America/Sao_Paulo", flag: "🇧🇷" },
  { city: "Riyadh", country: "Saudi Arabia", timezone: "Asia/Riyadh", flag: "🇸🇦" },
  { city: "Rome", country: "Italy", timezone: "Europe/Rome", flag: "🇮🇹" },
  { city: "Seoul", country: "South Korea", timezone: "Asia/Seoul", flag: "🇰🇷" },
  { city: "Shanghai", country: "China", timezone: "Asia/Shanghai", flag: "🇨🇳" },
  { city: "Singapore", country: "Singapore", timezone: "Asia/Singapore", flag: "🇸🇬" },
  { city: "Sydney", country: "Australia", timezone: "Australia/Sydney", flag: "🇦🇺" },
  { city: "Tokyo", country: "Japan", timezone: "Asia/Tokyo", flag: "🇯🇵" },
  { city: "Toronto", country: "Canada", timezone: "America/Toronto", flag: "🇨🇦" },
  { city: "Vancouver", country: "Canada", timezone: "America/Vancouver", flag: "🇨🇦" }
];
